# Generated by Django 4.2.16 on 2024-10-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstop',
            name='googleMapId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
