# Generated by Django 3.2.23 on 2024-10-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_fuelstop_googlemapid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
